"""Stub adapters for countries whose live integration isn't built yet.

Spec rule: no mock data. These return AdapterNotImplementedError on calls and
report `not_implemented` health, so the API layer can surface a clear 501.

This registry covers every ISO 3166-1 alpha-2 sovereign state (plus a few
widely-used dependencies). Real adapters in `_build_real_adapters()` override
these entries, so adding a real country only requires removing nothing here.
"""
from __future__ import annotations

from packages.adapters._base.adapter import NotImplementedAdapter
from packages.shared.models import IdentifierType


def _stub(
    cc: str,
    name: str,
    identifier_types: list[IdentifierType] | None = None,
    notes: str = "Adapter not implemented yet.",
) -> NotImplementedAdapter:
    return NotImplementedAdapter(
        country_code=cc,
        country_name=name,
        identifier_types=identifier_types or [IdentifierType.OTHER],
        notes=notes,
    )


_DEFAULT_VAT = [IdentifierType.VAT, IdentifierType.OTHER]
_DEFAULT_REG = [IdentifierType.COMPANY_NUMBER, IdentifierType.OTHER]


def build_stub_registry() -> dict[str, NotImplementedAdapter]:
    """One entry per ISO 3166-1 alpha-2 sovereign state.

    Order is region-grouped only for readability; key lookup is by upper-cased
    code regardless of insertion order.
    """
    return {
        # --- Europe ---
        "AD": _stub("AD", "Andorra", _DEFAULT_VAT, "Govern d'Andorra registre — paid, scrape only."),
        "AL": _stub("AL", "Albania", _DEFAULT_REG, "QKR (National Business Center) public partial."),
        "AT": _stub("AT", "Austria", _DEFAULT_REG, "See docs/countries/at.md."),
        "BA": _stub("BA", "Bosnia and Herzegovina", _DEFAULT_REG, "Federal/RS registers fragmented."),
        "BE": _stub("BE", "Belgium", _DEFAULT_VAT, "See docs/countries/be.md."),
        "BG": _stub("BG", "Bulgaria", _DEFAULT_REG, "See docs/countries/bg.md."),
        "BY": _stub("BY", "Belarus", _DEFAULT_VAT, "See docs/countries/by.md."),
        "CH": _stub("CH", "Switzerland", _DEFAULT_VAT, "See docs/countries/ch.md."),
        "CY": _stub("CY", "Cyprus", _DEFAULT_REG, "See docs/countries/cy.md."),
        "CZ": _stub("CZ", "Czechia", _DEFAULT_REG, "See docs/countries/cz.md."),
        "DE": _stub("DE", "Germany", [IdentifierType.HRB, IdentifierType.VAT], "See docs/countries/de.md."),
        "DK": _stub("DK", "Denmark", [IdentifierType.CVR], "See docs/countries/dk.md."),
        "EE": _stub("EE", "Estonia", _DEFAULT_REG, "See docs/countries/ee.md."),
        "ES": _stub("ES", "Spain", [IdentifierType.CIF, IdentifierType.NIF], "See docs/countries/es.md."),
        "FI": _stub("FI", "Finland", [IdentifierType.BUSINESS_ID], "See docs/countries/fi.md."),
        "FO": _stub("FO", "Faroe Islands", _DEFAULT_REG, "Faroese Skraseting partial."),
        "FR": _stub("FR", "France", [IdentifierType.SIREN, IdentifierType.SIRET], "See docs/countries/fr.md."),
        "GB": _stub("GB", "United Kingdom", [IdentifierType.COMPANY_NUMBER], "See docs/countries/uk.md."),
        "GG": _stub("GG", "Guernsey", _DEFAULT_REG, "Guernsey Registry — paid extracts."),
        "GI": _stub("GI", "Gibraltar", _DEFAULT_REG, "Companies House Gibraltar — paid."),
        "GR": _stub("GR", "Greece", _DEFAULT_REG, "See docs/countries/gr.md."),
        "HR": _stub("HR", "Croatia", _DEFAULT_VAT, "See docs/countries/hr.md."),
        "HU": _stub("HU", "Hungary", _DEFAULT_REG, "See docs/countries/hu.md."),
        "IE": _stub("IE", "Ireland", _DEFAULT_REG, "See docs/countries/ie.md."),
        "IM": _stub("IM", "Isle of Man", _DEFAULT_REG, "Isle of Man Companies Registry — partial free."),
        "IS": _stub("IS", "Iceland", _DEFAULT_REG, "Skatturinn HLU public search, free."),
        "IT": _stub("IT", "Italy", _DEFAULT_VAT, "See docs/countries/it.md."),
        "JE": _stub("JE", "Jersey", _DEFAULT_REG, "Jersey Financial Services Commission — partial free."),
        "LI": _stub("LI", "Liechtenstein", _DEFAULT_REG, "Handelsregister LI — paid extracts."),
        "LT": _stub("LT", "Lithuania", _DEFAULT_REG, "See docs/countries/lt.md."),
        "LU": _stub("LU", "Luxembourg", _DEFAULT_REG, "See docs/countries/lu.md."),
        "LV": _stub("LV", "Latvia", _DEFAULT_REG, "See docs/countries/lv.md."),
        "MC": _stub("MC", "Monaco", _DEFAULT_REG, "Répertoire du Commerce — paid."),
        "MD": _stub("MD", "Moldova", _DEFAULT_REG, "ASP / CSI partial public."),
        "ME": _stub("ME", "Montenegro", _DEFAULT_REG, "CRPS public partial."),
        "MK": _stub("MK", "North Macedonia", _DEFAULT_REG, "Central Registry partial public."),
        "MT": _stub("MT", "Malta", _DEFAULT_REG, "See docs/countries/mt.md."),
        "NL": _stub("NL", "Netherlands", [IdentifierType.KVK], "See docs/countries/nl.md."),
        "NO": _stub("NO", "Norway", [IdentifierType.ORG_NR], "See docs/countries/no.md."),
        "PL": _stub("PL", "Poland", [IdentifierType.KRS, IdentifierType.NIP, IdentifierType.REGON], "See docs/countries/pl.md."),
        "PT": _stub("PT", "Portugal", _DEFAULT_VAT, "See docs/countries/pt.md."),
        "RO": _stub("RO", "Romania", _DEFAULT_VAT, "See docs/countries/ro.md."),
        "RS": _stub("RS", "Serbia", _DEFAULT_REG, "APR (Serbian Business Registers Agency) public partial."),
        "RU": _stub("RU", "Russia", _DEFAULT_REG, "egrul.nalog.ru public lookup; sanctions caveats apply."),
        "SE": _stub("SE", "Sweden", [IdentifierType.ORG_NR], "See docs/countries/se.md."),
        "SI": _stub("SI", "Slovenia", _DEFAULT_REG, "See docs/countries/si.md."),
        "SK": _stub("SK", "Slovakia", [IdentifierType.ICO], "See docs/countries/sk.md."),
        "SM": _stub("SM", "San Marino", _DEFAULT_REG, "Camera di Commercio SM — paid."),
        "UA": _stub("UA", "Ukraine", _DEFAULT_REG, "See docs/countries/ua.md."),
        "VA": _stub("VA", "Vatican City", _DEFAULT_REG, "No public commercial register."),
        "XK": _stub("XK", "Kosovo", _DEFAULT_REG, "ARBK public partial."),

        # --- Asia ---
        "AF": _stub("AF", "Afghanistan", _DEFAULT_REG, "ACBR limited / political situation."),
        "AM": _stub("AM", "Armenia", _DEFAULT_VAT, "See docs/countries/am.md."),
        "AZ": _stub("AZ", "Azerbaijan", _DEFAULT_VAT, "See docs/countries/az.md."),
        "BD": _stub("BD", "Bangladesh", _DEFAULT_REG, "RJSC public partial."),
        "BH": _stub("BH", "Bahrain", _DEFAULT_REG, "MoIC commercial register partial."),
        "BN": _stub("BN", "Brunei", _DEFAULT_REG, "ROCBN partial."),
        "BT": _stub("BT", "Bhutan", _DEFAULT_REG, "MoEA Bhutan limited."),
        "CN": _stub("CN", "China", _DEFAULT_REG, "gsxt.gov.cn CAPTCHA-gated; Tianyancha paid."),
        "GE": _stub("GE", "Georgia", _DEFAULT_VAT, "See docs/countries/ge.md."),
        "HK": _stub("HK", "Hong Kong", _DEFAULT_REG, "See docs/countries/hk.md."),
        "ID": _stub("ID", "Indonesia", _DEFAULT_VAT, "See docs/countries/id.md."),
        "IL": _stub("IL", "Israel", _DEFAULT_REG, "See docs/countries/il.md."),
        "IN": _stub("IN", "India", _DEFAULT_REG, "See docs/countries/in.md."),
        "IQ": _stub("IQ", "Iraq", _DEFAULT_REG, "Ministry of Trade Iraq limited."),
        "IR": _stub("IR", "Iran", _DEFAULT_REG, "ssaa.ir / sanctions caveats."),
        "JO": _stub("JO", "Jordan", _DEFAULT_REG, "MIT Jordan partial."),
        "JP": _stub("JP", "Japan", _DEFAULT_REG, "See docs/countries/jp.md."),
        "KG": _stub("KG", "Kyrgyzstan", _DEFAULT_REG, "Min Justice KG partial."),
        "KH": _stub("KH", "Cambodia", _DEFAULT_REG, "MoC Cambodia partial."),
        "KP": _stub("KP", "North Korea", _DEFAULT_REG, "No public registry; sanctions."),
        "KR": _stub("KR", "South Korea", _DEFAULT_REG, "See docs/countries/kr.md."),
        "KW": _stub("KW", "Kuwait", _DEFAULT_REG, "MOCI Kuwait partial."),
        "KZ": _stub("KZ", "Kazakhstan", _DEFAULT_VAT, "See docs/countries/kz.md."),
        "LA": _stub("LA", "Laos", _DEFAULT_REG, "MoIC Laos limited."),
        "LB": _stub("LB", "Lebanon", _DEFAULT_REG, "Commercial Register limited."),
        "LK": _stub("LK", "Sri Lanka", _DEFAULT_REG, "DRC public partial."),
        "MM": _stub("MM", "Myanmar", _DEFAULT_REG, "DICA MyCO partial; sanctions caveats."),
        "MN": _stub("MN", "Mongolia", _DEFAULT_REG, "GASI partial."),
        "MO": _stub("MO", "Macao", _DEFAULT_REG, "DSAJ Macao partial."),
        "MV": _stub("MV", "Maldives", _DEFAULT_REG, "MED Maldives partial."),
        "MY": _stub("MY", "Malaysia", _DEFAULT_REG, "See docs/countries/my.md."),
        "NP": _stub("NP", "Nepal", _DEFAULT_REG, "OCR Nepal partial."),
        "OM": _stub("OM", "Oman", _DEFAULT_REG, "MoCI Oman partial."),
        "PH": _stub("PH", "Philippines", _DEFAULT_REG, "See docs/countries/ph.md."),
        "PK": _stub("PK", "Pakistan", _DEFAULT_REG, "SECP public name search."),
        "PS": _stub("PS", "Palestine", _DEFAULT_REG, "MoNE / sanctions caveats."),
        "QA": _stub("QA", "Qatar", _DEFAULT_REG, "MoCI Qatar partial."),
        "SA": _stub("SA", "Saudi Arabia", _DEFAULT_REG, "See docs/countries/sa.md."),
        "SG": _stub("SG", "Singapore", _DEFAULT_REG, "See docs/countries/sg.md."),
        "SY": _stub("SY", "Syria", _DEFAULT_REG, "Sanctions caveats; no public register."),
        "TH": _stub("TH", "Thailand", _DEFAULT_REG, "See docs/countries/th.md."),
        "TJ": _stub("TJ", "Tajikistan", _DEFAULT_REG, "Min Justice TJ partial."),
        "TL": _stub("TL", "Timor-Leste", _DEFAULT_REG, "SERVE partial."),
        "TM": _stub("TM", "Turkmenistan", _DEFAULT_REG, "No public register; political situation."),
        "TR": _stub("TR", "Türkiye", [IdentifierType.VKN, IdentifierType.MERSIS], "See docs/countries/tr.md."),
        "TW": _stub("TW", "Taiwan", [IdentifierType.VAT], "See docs/countries/tw.md."),
        "UZ": _stub("UZ", "Uzbekistan", _DEFAULT_REG, "Stat.uz partial."),
        "VN": _stub("VN", "Vietnam", _DEFAULT_REG, "See docs/countries/vn.md."),
        "YE": _stub("YE", "Yemen", _DEFAULT_REG, "Sanctions / political situation."),

        # --- Middle East & UAE specials ---
        "AE": _stub("AE", "United Arab Emirates", _DEFAULT_REG, "DED per-emirate fragmented; DIFC/ADGM separate."),

        # --- Africa ---
        "AO": _stub("AO", "Angola", _DEFAULT_REG, "GUE Angola partial."),
        "BF": _stub("BF", "Burkina Faso", _DEFAULT_REG, "RCCM West Africa partial."),
        "BI": _stub("BI", "Burundi", _DEFAULT_REG, "API Burundi partial."),
        "BJ": _stub("BJ", "Benin", _DEFAULT_REG, "GUFE/RCCM partial."),
        "BW": _stub("BW", "Botswana", _DEFAULT_REG, "CIPA Botswana partial."),
        "CD": _stub("CD", "DR Congo", _DEFAULT_REG, "Guichet Unique Congo partial."),
        "CF": _stub("CF", "Central African Republic", _DEFAULT_REG, "Sanctions / political situation."),
        "CG": _stub("CG", "Congo-Brazzaville", _DEFAULT_REG, "ANARM partial."),
        "CI": _stub("CI", "Côte d'Ivoire", _DEFAULT_REG, "CEPICI partial."),
        "CM": _stub("CM", "Cameroon", _DEFAULT_REG, "API Cameroon partial."),
        "CV": _stub("CV", "Cape Verde", _DEFAULT_REG, "Casa do Cidadão partial."),
        "DJ": _stub("DJ", "Djibouti", _DEFAULT_REG, "MoCI Djibouti partial."),
        "DZ": _stub("DZ", "Algeria", _DEFAULT_REG, "CNRC Algeria partial."),
        "EG": _stub("EG", "Egypt", _DEFAULT_REG, "See docs/countries/eg.md."),
        "EH": _stub("EH", "Western Sahara", _DEFAULT_REG, "Disputed territory."),
        "ER": _stub("ER", "Eritrea", _DEFAULT_REG, "Sanctions / no public registry."),
        "ET": _stub("ET", "Ethiopia", _DEFAULT_REG, "MoTI Ethiopia partial."),
        "GA": _stub("GA", "Gabon", _DEFAULT_REG, "ANPI partial."),
        "GH": _stub("GH", "Ghana", _DEFAULT_REG, "RGD public web partial."),
        "GM": _stub("GM", "Gambia", _DEFAULT_REG, "MoTRIE partial."),
        "GN": _stub("GN", "Guinea", _DEFAULT_REG, "APIP Guinea partial."),
        "GQ": _stub("GQ", "Equatorial Guinea", _DEFAULT_REG, "MINECOMI partial."),
        "GW": _stub("GW", "Guinea-Bissau", _DEFAULT_REG, "GUE partial."),
        "KE": _stub("KE", "Kenya", _DEFAULT_REG, "See docs/countries/ke.md."),
        "KM": _stub("KM", "Comoros", _DEFAULT_REG, "ANPI Comores partial."),
        "LR": _stub("LR", "Liberia", _DEFAULT_REG, "LBR partial; offshore notoriety."),
        "LS": _stub("LS", "Lesotho", _DEFAULT_REG, "MTICM partial."),
        "LY": _stub("LY", "Libya", _DEFAULT_REG, "Sanctions / political situation."),
        "MA": _stub("MA", "Morocco", _DEFAULT_VAT, "See docs/countries/ma.md."),
        "MG": _stub("MG", "Madagascar", _DEFAULT_REG, "EDBM partial."),
        "ML": _stub("ML", "Mali", _DEFAULT_REG, "API Mali partial."),
        "MR": _stub("MR", "Mauritania", _DEFAULT_REG, "MoT Mauritania partial."),
        "MU": _stub("MU", "Mauritius", _DEFAULT_REG, "ROC Mauritius — paid extracts."),
        "MW": _stub("MW", "Malawi", _DEFAULT_REG, "MITC Malawi partial."),
        "MZ": _stub("MZ", "Mozambique", _DEFAULT_REG, "Boletim da República partial."),
        "NA": _stub("NA", "Namibia", _DEFAULT_REG, "BIPA Namibia partial."),
        "NE": _stub("NE", "Niger", _DEFAULT_REG, "Maison de l'Entreprise partial."),
        "NG": _stub("NG", "Nigeria", _DEFAULT_REG, "See docs/countries/ng.md."),
        "RE": _stub("RE", "Réunion", _DEFAULT_REG, "French overseas dept — covered by FR SIREN."),
        "RW": _stub("RW", "Rwanda", _DEFAULT_REG, "RDB public partial."),
        "SC": _stub("SC", "Seychelles", _DEFAULT_REG, "FSA Seychelles — paid; offshore notoriety."),
        "SD": _stub("SD", "Sudan", _DEFAULT_REG, "Sanctions / political situation."),
        "SH": _stub("SH", "Saint Helena", _DEFAULT_REG, "Companies Registry — paid."),
        "SL": _stub("SL", "Sierra Leone", _DEFAULT_REG, "OARG partial."),
        "SN": _stub("SN", "Senegal", _DEFAULT_REG, "APIX partial."),
        "SO": _stub("SO", "Somalia", _DEFAULT_REG, "No public registry; political situation."),
        "SS": _stub("SS", "South Sudan", _DEFAULT_REG, "No public registry; political situation."),
        "ST": _stub("ST", "São Tomé and Príncipe", _DEFAULT_REG, "Guichet Único partial."),
        "SZ": _stub("SZ", "Eswatini", _DEFAULT_REG, "Min Commerce Eswatini partial."),
        "TD": _stub("TD", "Chad", _DEFAULT_REG, "ANIE Chad partial."),
        "TG": _stub("TG", "Togo", _DEFAULT_REG, "CFE Togo partial."),
        "TN": _stub("TN", "Tunisia", _DEFAULT_REG, "Registre National des Entreprises partial."),
        "TZ": _stub("TZ", "Tanzania", _DEFAULT_REG, "BRELA partial."),
        "UG": _stub("UG", "Uganda", _DEFAULT_REG, "URSB partial."),
        "YT": _stub("YT", "Mayotte", _DEFAULT_REG, "French overseas — covered by FR SIREN."),
        "ZA": _stub("ZA", "South Africa", _DEFAULT_REG, "See docs/countries/za.md."),
        "ZM": _stub("ZM", "Zambia", _DEFAULT_REG, "PACRA partial."),
        "ZW": _stub("ZW", "Zimbabwe", _DEFAULT_REG, "Companies Office partial."),

        # --- Americas ---
        "AG": _stub("AG", "Antigua and Barbuda", _DEFAULT_REG, "ABIPCO — paid."),
        "AI": _stub("AI", "Anguilla", _DEFAULT_REG, "ASCR — paid; offshore."),
        "AR": _stub("AR", "Argentina", _DEFAULT_VAT, "See docs/countries/ar.md."),
        "AW": _stub("AW", "Aruba", _DEFAULT_REG, "KvK Aruba — partial."),
        "BB": _stub("BB", "Barbados", _DEFAULT_REG, "CAIPO — partial."),
        "BL": _stub("BL", "Saint Barthélemy", _DEFAULT_REG, "French — covered by FR SIREN."),
        "BM": _stub("BM", "Bermuda", _DEFAULT_REG, "Registrar Bermuda — paid; offshore."),
        "BO": _stub("BO", "Bolivia", _DEFAULT_REG, "SEPREC public partial."),
        "BQ": _stub("BQ", "Caribbean Netherlands", _DEFAULT_REG, "KvK BES — partial."),
        "BR": _stub("BR", "Brazil", _DEFAULT_VAT, "See docs/countries/br.md."),
        "BS": _stub("BS", "Bahamas", _DEFAULT_REG, "Registrar General — paid; offshore."),
        "BZ": _stub("BZ", "Belize", _DEFAULT_REG, "FSC Belize — paid; offshore."),
        "CA": _stub("CA", "Canada", _DEFAULT_REG, "See docs/countries/ca.md."),
        "CL": _stub("CL", "Chile", _DEFAULT_VAT, "See docs/countries/cl.md."),
        "CO": _stub("CO", "Colombia", _DEFAULT_VAT, "See docs/countries/co.md."),
        "CR": _stub("CR", "Costa Rica", _DEFAULT_REG, "RNP public partial."),
        "CU": _stub("CU", "Cuba", _DEFAULT_REG, "Sanctions; no public registry."),
        "CW": _stub("CW", "Curaçao", _DEFAULT_REG, "KvK Curaçao — partial."),
        "DM": _stub("DM", "Dominica", _DEFAULT_REG, "CIPO Dominica — partial."),
        "DO": _stub("DO", "Dominican Republic", _DEFAULT_REG, "DGII partial."),
        "EC": _stub("EC", "Ecuador", _DEFAULT_VAT, "SUPERCIAS public web partial."),
        "GD": _stub("GD", "Grenada", _DEFAULT_REG, "CAIPO Grenada — partial."),
        "GF": _stub("GF", "French Guiana", _DEFAULT_REG, "French — covered by FR SIREN."),
        "GL": _stub("GL", "Greenland", _DEFAULT_REG, "Danish — covered by DK CVR."),
        "GP": _stub("GP", "Guadeloupe", _DEFAULT_REG, "French — covered by FR SIREN."),
        "GT": _stub("GT", "Guatemala", _DEFAULT_REG, "Registro Mercantil partial."),
        "GY": _stub("GY", "Guyana", _DEFAULT_REG, "DCR Guyana — partial."),
        "HN": _stub("HN", "Honduras", _DEFAULT_REG, "Cámara de Comercio per-region."),
        "HT": _stub("HT", "Haiti", _DEFAULT_REG, "MCI Haiti partial."),
        "JM": _stub("JM", "Jamaica", _DEFAULT_REG, "COJ public partial."),
        "KN": _stub("KN", "Saint Kitts and Nevis", _DEFAULT_REG, "Registrar — paid; offshore notoriety."),
        "KY": _stub("KY", "Cayman Islands", _DEFAULT_REG, "Registrar — paid; offshore."),
        "LC": _stub("LC", "Saint Lucia", _DEFAULT_REG, "Registry Lucia — partial."),
        "MF": _stub("MF", "Saint Martin", _DEFAULT_REG, "French — covered by FR SIREN."),
        "MQ": _stub("MQ", "Martinique", _DEFAULT_REG, "French — covered by FR SIREN."),
        "MS": _stub("MS", "Montserrat", _DEFAULT_REG, "FSC Montserrat — paid."),
        "MX": _stub("MX", "Mexico", _DEFAULT_VAT, "See docs/countries/mx.md."),
        "NI": _stub("NI", "Nicaragua", _DEFAULT_REG, "DGI partial."),
        "PA": _stub("PA", "Panama", _DEFAULT_REG, "Registro Público — partial; offshore notoriety."),
        "PE": _stub("PE", "Peru", _DEFAULT_VAT, "See docs/countries/pe.md."),
        "PM": _stub("PM", "Saint Pierre and Miquelon", _DEFAULT_REG, "French — covered by FR SIREN."),
        "PR": _stub("PR", "Puerto Rico", _DEFAULT_REG, "US territory — covered by US adapter."),
        "PY": _stub("PY", "Paraguay", _DEFAULT_REG, "SET Paraguay partial."),
        "SR": _stub("SR", "Suriname", _DEFAULT_REG, "KKF partial."),
        "SV": _stub("SV", "El Salvador", _DEFAULT_REG, "CNR partial."),
        "SX": _stub("SX", "Sint Maarten", _DEFAULT_REG, "KvK Sint Maarten — partial."),
        "TC": _stub("TC", "Turks and Caicos Islands", _DEFAULT_REG, "FSC TCI — paid; offshore."),
        "TT": _stub("TT", "Trinidad and Tobago", _DEFAULT_REG, "MIC TT partial."),
        "US": _stub("US", "United States", [IdentifierType.EIN, IdentifierType.CIK], "See docs/countries/us.md."),
        "UY": _stub("UY", "Uruguay", _DEFAULT_VAT, "See docs/countries/uy.md."),
        "VC": _stub("VC", "Saint Vincent and the Grenadines", _DEFAULT_REG, "FSA SVG — paid; offshore."),
        "VE": _stub("VE", "Venezuela", _DEFAULT_REG, "SAREN partial; sanctions caveats."),
        "VG": _stub("VG", "British Virgin Islands", _DEFAULT_REG, "FSC BVI — paid; offshore."),
        "VI": _stub("VI", "US Virgin Islands", _DEFAULT_REG, "US territory."),

        # --- Oceania ---
        "AS": _stub("AS", "American Samoa", _DEFAULT_REG, "US territory."),
        "AU": _stub("AU", "Australia", _DEFAULT_VAT, "See docs/countries/au.md."),
        "CK": _stub("CK", "Cook Islands", _DEFAULT_REG, "FSC Cook Islands — paid; offshore."),
        "FJ": _stub("FJ", "Fiji", _DEFAULT_REG, "Registrar Fiji partial."),
        "FM": _stub("FM", "Micronesia", _DEFAULT_REG, "FSM Registrar limited."),
        "GU": _stub("GU", "Guam", _DEFAULT_REG, "US territory."),
        "KI": _stub("KI", "Kiribati", _DEFAULT_REG, "MCIC partial."),
        "MH": _stub("MH", "Marshall Islands", _DEFAULT_REG, "Registrar — paid; offshore."),
        "MP": _stub("MP", "Northern Mariana Islands", _DEFAULT_REG, "US territory."),
        "NC": _stub("NC", "New Caledonia", _DEFAULT_REG, "French — covered by FR SIREN."),
        "NF": _stub("NF", "Norfolk Island", _DEFAULT_REG, "Australian — covered by AU ABN."),
        "NR": _stub("NR", "Nauru", _DEFAULT_REG, "Registrar — paid; offshore."),
        "NU": _stub("NU", "Niue", _DEFAULT_REG, "Small offshore."),
        "NZ": _stub("NZ", "New Zealand", _DEFAULT_REG, "See docs/countries/nz.md."),
        "PF": _stub("PF", "French Polynesia", _DEFAULT_REG, "French — covered by FR SIREN."),
        "PG": _stub("PG", "Papua New Guinea", _DEFAULT_REG, "IPA Niugini partial."),
        "PN": _stub("PN", "Pitcairn", _DEFAULT_REG, "Tiny territory."),
        "PW": _stub("PW", "Palau", _DEFAULT_REG, "Registrar partial."),
        "SB": _stub("SB", "Solomon Islands", _DEFAULT_REG, "Registrar partial."),
        "TK": _stub("TK", "Tokelau", _DEFAULT_REG, "Small territory."),
        "TO": _stub("TO", "Tonga", _DEFAULT_REG, "MCCTL partial."),
        "TV": _stub("TV", "Tuvalu", _DEFAULT_REG, "Small offshore."),
        "VU": _stub("VU", "Vanuatu", _DEFAULT_REG, "VFSC — paid; offshore."),
        "WF": _stub("WF", "Wallis and Futuna", _DEFAULT_REG, "French — covered by FR SIREN."),
        "WS": _stub("WS", "Samoa", _DEFAULT_REG, "MCIL — paid; offshore."),
    }
