"""Write one research markdown per country into docs/countries/."""
from pathlib import Path

DOCS_DIR = Path(__file__).resolve().parents[1] / "docs" / "countries"

DOCS: dict[str, dict[str, str]] = {
    "uk": {
        "title": "🇬🇧 United Kingdom — Companies House",
        "ident_type": "COMPANY_NUMBER",
        "ident_fmt": "8-character alphanumeric, numeric values zero-padded (e.g. 00102498 = BP).",
        "urls": "https://developer.company-information.service.gov.uk",
        "auth": "Yes — `UK_COMPANIES_HOUSE_API_KEY` (free, instant signup).",
        "rate": "600 req / 5 min.",
        "robots": "ToS allows API use; web scraping discouraged.",
        "tests": "BP p.l.c. (00102498); HSBC Holdings plc (00617987); Vodafone Group plc (01833679).",
        "status": "✅ **Live** — search + lookup + financials (PDF document URLs).",
        "next": "Plug in pypdf/pdfplumber extraction so the LLM can read filed accounts text.",
    },
    "us": {
        "title": "🇺🇸 United States — SEC EDGAR",
        "ident_type": "CIK",
        "ident_fmt": "10-digit, zero-padded. Example: 0000320193 = Apple Inc.",
        "urls": "https://www.sec.gov/cgi-bin/browse-edgar ; https://data.sec.gov",
        "auth": "No key — but the SEC requires a descriptive User-Agent with contact email (`SEC_EDGAR_USER_AGENT`).",
        "rate": "10 req/sec (global SEC rule).",
        "robots": "Allowed under the SEC's documented UA rule.",
        "tests": "Apple Inc. (0000320193); Microsoft (0000789019); Tesla (0001318605).",
        "status": "✅ **Live** — search + lookup + structured XBRL financials.",
        "next": "Add state-level Secretary-of-State adapters (DE, CA, NY, TX, FL) — EDGAR only covers SEC-registered issuers.",
    },
    "fr": {
        "title": "🇫🇷 France — recherche-entreprises.api.gouv.fr (INSEE + INPI)",
        "ident_type": "SIREN / SIRET",
        "ident_fmt": "SIREN = 9 digits, SIRET = 14 digits (SIREN + 5).",
        "urls": "https://api.gouv.fr/documentation/api-recherche-entreprises",
        "auth": "No key required.",
        "rate": "7 req/sec (documented).",
        "robots": "Open data — allowed.",
        "tests": "TotalEnergies SE (SIREN 542051180); Carrefour (652014051); Renault (441639465).",
        "status": "🟡 **Partial** — search + lookup ✅; financials require INPI OAuth (`comptes annuels`) — not in MVP.",
        "next": "Wire INPI OAuth to fetch `comptes annuels` PDFs.",
    },
    "nl": {
        "title": "🇳🇱 Netherlands — KvK Handelsregister",
        "ident_type": "KVK",
        "ident_fmt": "8 digits. Example: 17014545 = ASML Holding N.V.",
        "urls": "https://developers.kvk.nl/",
        "auth": "Yes — `NL_KVK_API_KEY`. Test env is free; production is paid.",
        "rate": "60 req/min on test.",
        "robots": "Per KvK ToS — API only.",
        "tests": "ASML (17014545); Royal Philips (17001910); Heineken (33011433).",
        "status": "🟡 **Degraded** — needs API key. Lookup + search work; financials require deposited-accounts (paid) integration.",
        "next": "Move to KvK production tier + integrate `gedeponeerde jaarrekeningen` retrieval.",
    },
    "cz": {
        "title": "🇨🇿 Czech Republic — ARES",
        "ident_type": "ICO",
        "ident_fmt": "8 digits. Example: 45274649 = ČEZ, a. s.",
        "urls": "https://ares.gov.cz/",
        "auth": "No — free public REST API.",
        "rate": "Soft ~60 req/min.",
        "robots": "Open data — allowed.",
        "tests": "ČEZ a.s. (45274649); Škoda Auto (00177041); Komerční banka (45317054).",
        "status": "🟡 **Partial** — search + lookup ✅; filings via Sbírka listin (justice.cz) are PDF-only.",
        "next": "Scrape Sbírka listin per IČO and link out to PDFs.",
    },
    "ee": {
        "title": "🇪🇪 Estonia — Äriregister",
        "ident_type": "BUSINESS_ID (registrikood)",
        "ident_fmt": "8 digits.",
        "urls": "https://www.ariregister.rik.ee/; https://avaandmed.ariregister.rik.ee/",
        "auth": "Live search requires Ariregister contract; bulk open-data dumps are free.",
        "rate": "n/a for bulk.",
        "robots": "OK for bulk; live API per contract.",
        "tests": "Bolt Technology OÜ (12417834); Veriff OÜ; Wise (Estonia) OÜ.",
        "status": "🟡 **Lookup-only stub** linking to inforegister.ee. Live search needs paid contract.",
        "next": "Ingest the periodic Ariregister open-data dump into Postgres for search.",
    },
    "no": {
        "title": "🇳🇴 Norway — Brønnøysund (Brreg)",
        "ident_type": "ORG_NR",
        "ident_fmt": "9 digits. Example: 923609016 = Equinor ASA.",
        "urls": "https://data.brreg.no/enhetsregisteret/api/",
        "auth": "No — free open API.",
        "rate": "Generous, no published limit.",
        "robots": "Allowed.",
        "tests": "Equinor (923609016); Telenor (982463718); DNB Bank (984851006).",
        "status": "🟡 **Partial** — search + lookup ✅. Regnskapsregisteret PDFs not yet wired.",
        "next": "Implement Regnskapsregisteret document-service client (returns annual-account PDFs).",
    },
    "fi": {
        "title": "🇫🇮 Finland — PRH YTJ (Avoindata)",
        "ident_type": "BUSINESS_ID",
        "ident_fmt": "7 digits + checksum, formatted NNNNNNN-N. Example: 0112038-9 = Nokia Oyj.",
        "urls": "https://avoindata.prh.fi/opendata-ytj-api/v3",
        "auth": "No — free public API.",
        "rate": "60/min suggested.",
        "robots": "Allowed.",
        "tests": "Nokia (0112038-9); Kone (1927400-1); Fortum (1463611-4).",
        "status": "🟡 **Partial** — search + lookup ✅; financials are PRH paid service.",
        "next": "Subscribe to PRH financials feed or scrape published annual reports per company website.",
    },
    "de": {
        "title": "🇩🇪 Germany — Handelsregister",
        "ident_type": "HRB",
        "ident_fmt": "Court + HRB number (e.g. HRB 42243 München = BMW AG).",
        "urls": "https://www.handelsregister.de/; OffeneRegister.de mirror",
        "auth": "Bulk data paywalled; web search free but session-bound. OffeneRegister has free historical data.",
        "rate": "Web scrape only.",
        "robots": "Permitted with restraint.",
        "tests": "BMW AG (HRB 42243 München); SAP SE (HRB 719915); Volkswagen AG (HRB 100484 Braunschweig).",
        "status": "🔴 **Blocked for MVP** — handelsregister.de needs session + €1/document for filings.",
        "next": "Integrate OffeneRegister.de for free company data; charge for filings later.",
    },
    "pl": {
        "title": "🇵🇱 Poland — KRS + CEIDG + Biała Lista",
        "ident_type": "KRS / NIP / REGON",
        "ident_fmt": "KRS 10-digit; NIP 10-digit; REGON 9 or 14.",
        "urls": "https://api-krs.ms.gov.pl ; https://prod.ceidg.gov.pl ; https://wl-api.mf.gov.pl",
        "auth": "KRS REST is public; CEIDG free; Biała Lista free.",
        "rate": "Varies.",
        "robots": "Open data — allowed.",
        "tests": "PKN Orlen S.A. (KRS 0000028860, NIP 7740001454); CD Projekt (KRS 0000006865); Allegro.eu (KRS 0000635012).",
        "status": "🔴 **Not yet wired** — KRS JSON endpoint reachable via api-krs.ms.gov.pl; would be highest-value next adapter.",
        "next": "Implement KRS REST client + Biała Lista VAT validation for credit scoring.",
    },
    "es": {
        "title": "🇪🇸 Spain — BORME",
        "ident_type": "CIF",
        "ident_fmt": "Letter + 8 digits. Example: A15022510 = Inditex S.A.",
        "urls": "https://www.boe.es/diario_borme/",
        "auth": "BORME is a daily PDF publication; no free structured API.",
        "rate": "n/a (bulk PDF).",
        "robots": "OK with attribution.",
        "tests": "Inditex (A15022510); Telefónica (A28015865); BBVA (A48265169).",
        "status": "🔴 **Not yet wired** — would require BORME PDF parsing pipeline.",
        "next": "Use Datos.gob.es CSV exports of BORME entries as a daily ingestion source.",
    },
    "it": {
        "title": "🇮🇹 Italy — Registro Imprese (InfoCamere)",
        "ident_type": "VAT",
        "ident_fmt": "11 digits.",
        "urls": "https://www.registroimprese.it/",
        "auth": "Paid via InfoCamere; no free public API.",
        "rate": "Per contract.",
        "robots": "Per ToS.",
        "tests": "Eni S.p.A. (VAT 00484960588); Enel (00811720580); Ferrari N.V.",
        "status": "🔴 **Blocked for MVP** — requires paid InfoCamere subscription.",
        "next": "Wire VIES VAT validation as free fallback; assess InfoCamere paid tier.",
    },
    "be": {
        "title": "🇧🇪 Belgium — KBO/BCE",
        "ident_type": "OTHER (enterprise number)",
        "ident_fmt": "10 digits formatted NNNN.NNN.NNN.",
        "urls": "https://kbopub.economie.fgov.be/",
        "auth": "Free static open-data dump; live search via public web only.",
        "rate": "n/a (bulk).",
        "robots": "Allowed.",
        "tests": "AB InBev (0417.497.106); UCB (0403.053.608); Solvay (0403.091.220).",
        "status": "🔴 **Not yet wired** — KBO open-data CSV dump is the right ingestion path.",
        "next": "Ingest the KBO CSV dump nightly and expose search via Postgres.",
    },
    "se": {
        "title": "🇸🇪 Sweden — Bolagsverket",
        "ident_type": "ORG_NR",
        "ident_fmt": "10 digits formatted XXXXXX-XXXX.",
        "urls": "https://bolagsverket.se/",
        "auth": "Näringslivsregistret API is paid.",
        "rate": "Per contract.",
        "robots": "Per ToS.",
        "tests": "Volvo AB (556012-5790); H&M (556042-7220); Ericsson (556056-6258).",
        "status": "🔴 **Not yet wired** — paid API.",
        "next": "Evaluate allabolag.se as a non-official source for MVP (ToS-sensitive).",
    },
    "dk": {
        "title": "🇩🇰 Denmark — CVR",
        "ident_type": "CVR",
        "ident_fmt": "8 digits.",
        "urls": "https://datacvr.virk.dk/",
        "auth": "Free CVR open data; ElasticSearch endpoint needs free user registration.",
        "rate": "Per ToS.",
        "robots": "Allowed.",
        "tests": "Carlsberg (CVR 61056416); A.P. Møller — Mærsk (CVR 22756214); Novo Nordisk (24256790).",
        "status": "🔴 **Not yet wired** — operator must register at datacvr.virk.dk for an ES key.",
        "next": "Implement the CVR ES client once credentials provisioned.",
    },
    "ie": {
        "title": "🇮🇪 Ireland — CRO",
        "ident_type": "COMPANY_NUMBER",
        "ident_fmt": "1–7 digits.",
        "urls": "https://www.cro.ie/",
        "auth": "Open data PDFs free; structured per-company API is paid.",
        "rate": "Per ToS.",
        "robots": "Allowed.",
        "tests": "Ryanair Holdings plc; CRH plc; Smurfit Kappa.",
        "status": "🔴 **Not yet wired**.",
        "next": "Scrape CRO HTML company-search results as MVP; evaluate paid API later.",
    },
    "at": {
        "title": "🇦🇹 Austria — Firmenbuch / Justizportal",
        "ident_type": "OTHER (FN)",
        "ident_fmt": "FN + court code.",
        "urls": "https://justizonline.gv.at/; https://www.firmenabc.at/",
        "auth": "Justizportal requires citizen-card login (ID-Austria); FirmenABC partial free.",
        "rate": "Restricted.",
        "robots": "Restrictive.",
        "tests": "OMV AG (FN 93363q); Erste Group Bank (FN 33209m); voestalpine AG (FN 66209t).",
        "status": "🔴 **Blocked** — gov portal needs Austrian eID.",
        "next": "Scrape FirmenABC.at as MVP fallback (commercial use needs license).",
    },
    "sk": {
        "title": "🇸🇰 Slovakia — OR SR",
        "ident_type": "ICO",
        "ident_fmt": "8 digits.",
        "urls": "https://www.orsr.sk/; https://finstat.sk/",
        "auth": "OR SR public web; FinStat is paid.",
        "rate": "Per ToS.",
        "robots": "Allowed.",
        "tests": "Slovnaft a.s. (31322832); Tatra banka a.s. (00686930); Slovak Telekom (35763469).",
        "status": "🔴 **Not yet wired** — scraping OR SR is feasible.",
        "next": "Implement OR SR HTML scrape with respectful rate.",
    },
    "hu": {
        "title": "🇭🇺 Hungary — E-cégjegyzék",
        "ident_type": "OTHER (Cégjegyzékszám)",
        "ident_fmt": "Court code + sequential.",
        "urls": "https://www.e-cegjegyzek.hu/",
        "auth": "Public web; bulk access needs Hungarian eID.",
        "rate": "n/a.",
        "robots": "Per ToS.",
        "tests": "MOL Plc.; Richter Gedeon Nyrt.; OTP Bank Nyrt.",
        "status": "🔴 **Blocked** — needs Hungarian eID for bulk.",
        "next": "Use opten.hu/ceginfo.hu commercial APIs as alternative.",
    },
    "ro": {
        "title": "🇷🇴 Romania — ONRC",
        "ident_type": "OTHER (CUI)",
        "ident_fmt": "Numeric.",
        "urls": "https://www.onrc.ro/",
        "auth": "RECOM portal partial; full data behind paid contract.",
        "rate": "Per use.",
        "robots": "Per ToS.",
        "tests": "OMV Petrom S.A. (CUI 1590082); Banca Transilvania (CUI 5022670); Dacia (1747357).",
        "status": "🔴 **Blocked for structured data**.",
        "next": "Scrape termene.ro / risco.ro (paid alternatives for MVP).",
    },
    "bg": {
        "title": "🇧🇬 Bulgaria — Trade Register",
        "ident_type": "OTHER (EIK)",
        "ident_fmt": "9 digits.",
        "urls": "https://portal.registryagency.bg/",
        "auth": "Public search free; bulk API is paid.",
        "rate": "Per use.",
        "robots": "Per ToS.",
        "tests": "Sopharma AD (831902088); Lukoil Bulgaria EOOD.",
        "status": "🔴 **Not yet wired**.",
        "next": "Scrape public HTML search.",
    },
    "hr": {
        "title": "🇭🇷 Croatia — Sudski registar",
        "ident_type": "OTHER (OIB)",
        "ident_fmt": "11 digits.",
        "urls": "https://sudreg.pravosudje.hr/",
        "auth": "Public web; no JSON API.",
        "rate": "n/a.",
        "robots": "Per ToS.",
        "tests": "HEP d.d.; INA d.d. (OIB 27759560625); Atlantic Grupa.",
        "status": "🔴 **Not yet wired** — scraping required.",
        "next": "Scrape Sudski registar HTML.",
    },
    "si": {
        "title": "🇸🇮 Slovenia — AJPES",
        "ident_type": "OTHER (matična št.)",
        "ident_fmt": "7 digits.",
        "urls": "https://www.ajpes.si/",
        "auth": "Several free APIs; registration per use case.",
        "rate": "Varies.",
        "robots": "Per ToS.",
        "tests": "Krka d.d.; Petrol d.d.; Telekom Slovenije.",
        "status": "🔴 **Not yet wired** — AJPES has good APIs that would be a high-priority next.",
        "next": "Register at AJPES and implement ePRS-API client.",
    },
    "lt": {
        "title": "🇱🇹 Lithuania — Registrų centras",
        "ident_type": "OTHER",
        "ident_fmt": "9 digits.",
        "urls": "https://www.registrucentras.lt/",
        "auth": "Free name search; paid for structured extracts.",
        "rate": "Per use.",
        "robots": "Per ToS.",
        "tests": "Ignitis grupė AB; SBA Group; Lietuvos energija.",
        "status": "🔴 **Not yet wired**.",
        "next": "Scrape the public REGIA name-search HTML.",
    },
    "lv": {
        "title": "🇱🇻 Latvia — UR / Lursoft",
        "ident_type": "OTHER",
        "ident_fmt": "11 digits.",
        "urls": "https://www.ur.gov.lv/; https://www.lursoft.lv/",
        "auth": "Lursoft is paid; UR open data partial.",
        "rate": "Varies.",
        "robots": "Per ToS.",
        "tests": "airBaltic AS; Latvenergo AS.",
        "status": "🔴 **Not yet wired**.",
        "next": "Ingest UR open-data dump.",
    },
    "pt": {
        "title": "🇵🇹 Portugal — Portal da Empresa",
        "ident_type": "VAT (NIPC)",
        "ident_fmt": "9 digits NIPC.",
        "urls": "https://www.portaldaempresa.pt/",
        "auth": "Public search via web only.",
        "rate": "n/a.",
        "robots": "Per ToS.",
        "tests": "EDP S.A.; Galp Energia; Sonae SGPS.",
        "status": "🔴 **Not yet wired** — scrape feasible.",
        "next": "Scrape Portal da Empresa search; use VIES for VAT validation.",
    },
    "lu": {
        "title": "🇱🇺 Luxembourg — LBR/RCSL",
        "ident_type": "OTHER (RCSL)",
        "ident_fmt": "B + 5–6 digits.",
        "urls": "https://www.lbr.lu/",
        "auth": "Free PDF search; per-document fee for extracts.",
        "rate": "Per use.",
        "robots": "Per ToS.",
        "tests": "ArcelorMittal (B 82454); SES S.A. (B 81267).",
        "status": "🔴 **Not yet wired**.",
        "next": "Scrape lbr.lu public search.",
    },
    "mt": {
        "title": "🇲🇹 Malta — MBR",
        "ident_type": "OTHER",
        "ident_fmt": "C + digits.",
        "urls": "https://mbr.mt/",
        "auth": "Online search free; per-document fee.",
        "rate": "Per use.",
        "robots": "Per ToS.",
        "tests": "Bank of Valletta plc; HSBC Bank Malta plc.",
        "status": "🔴 **Not yet wired**.",
        "next": "Scrape MBR HTML search.",
    },
    "cy": {
        "title": "🇨🇾 Cyprus — DRCOR",
        "ident_type": "OTHER (HE)",
        "ident_fmt": "HE + digits.",
        "urls": "https://www.companies.gov.cy/",
        "auth": "Public web search; no structured API.",
        "rate": "n/a.",
        "robots": "Per ToS.",
        "tests": "Hellenic Bank Public Co Ltd; Bank of Cyprus PLC.",
        "status": "🔴 **Not yet wired**.",
        "next": "Scrape DRCOR HTML search.",
    },
    "gr": {
        "title": "🇬🇷 Greece — GEMI",
        "ident_type": "OTHER (GEMI)",
        "ident_fmt": "12 digits.",
        "urls": "https://www.businessportal.gr/",
        "auth": "Public web; KYC service is paid.",
        "rate": "Varies.",
        "robots": "Per ToS.",
        "tests": "OPAP S.A. (3823201000); Hellenic Petroleum; Coca-Cola HBC AG.",
        "status": "🔴 **Not yet wired**.",
        "next": "Scrape businessportal.gr; assess paid GEMI KYC for production.",
    },
    "tr": {
        "title": "🇹🇷 Türkiye — Ticaret Sicil + GİB",
        "ident_type": "VKN / MERSIS",
        "ident_fmt": "VKN 10 digits; MERSIS 16 digits.",
        "urls": "https://www.ticaretsicil.gov.tr/; https://mersis.gtb.gov.tr/; https://www.kap.org.tr/",
        "auth": "Most endpoints need Turkish eID; some MERSIS pages public; KAP feeds free for listed companies.",
        "rate": "Varies.",
        "robots": "Restrictive.",
        "tests": "Türk Hava Yolları A.O. (VKN 8350023902); Koç Holding A.Ş.; THY (KAP THYAO).",
        "status": "🔴 **Blocked** — gov portals need Turkish e-ID.",
        "next": "Integrate KAP (Public Disclosure Platform) JSON feeds for listed companies — free.",
    },
}


def render(cc: str, d: dict[str, str]) -> str:
    return f"""# {d['title']}

## Identifier

- Type: `{d['ident_type']}`
- Format: {d['ident_fmt']}

## Sources

- {d['urls']}
- **Auth**: {d['auth']}
- **Rate limit**: {d['rate']}
- **robots.txt / ToS**: {d['robots']}

## Test companies

- {d['tests']}

## Status

{d['status']}

**Recommended next step:** {d['next']}
"""


def main() -> None:
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    for cc, d in DOCS.items():
        (DOCS_DIR / f"{cc}.md").write_text(render(cc, d), encoding="utf-8")
    print(f"Wrote {len(DOCS)} country docs to {DOCS_DIR}")


if __name__ == "__main__":
    main()
