"""Peru adapter — SUNAT (RUC verifier) + SMV (listed-company filings).

Sources:
- SUNAT public RUC verifier:
  https://e-consultaruc.sunat.gob.pe/cl-ti-itmrconsruc/jcrS00Alias — HTML
  form, free, no key. Per-RUC lookup goes via the `jcrS00Alias` JSP
  endpoint with parameters `accion=consPorRuc&nroRuc={ruc}`. The
  response is a small HTML page with labelled rows (Número de RUC,
  Tipo Contribuyente, Nombre o Razón Social, Estado, Condición,
  Dirección, Actividad Económica). Layout shifts occasionally so the
  scrape is defensive: regex against label text, never trust positions.
- SMV (Superintendencia del Mercado de Valores): free, public.
  https://www.smv.gob.pe/Frm_InformacionFinanciera.aspx?data={ruc} is
  the discovery URL for a company's filed audited annual reports. SMV
  only covers listed/regulated entities; for everyone else `fetch_financials`
  returns `[]` (per the no-mock-data rule).

Identifier: **RUC** (Registro Único de Contribuyentes) — 11 digits. The
first two digits indicate the contributor type; `20` is the prefix for
companies (personas jurídicas). RUC doubles as the Peruvian corporate
tax/VAT identifier, so we expose it primarily as `VAT` and also accept
`COMPANY_NUMBER` as an alias. We deliberately do NOT enforce a Mod-11
checksum: SUNAT's published algorithm (weights 5,4,3,2,7,6,5,4,3,2)
does not match every live RUC — historical/transitional records exist
that fail strict validation but are nonetheless valid in SUNAT's
database. Per the no-mock-data rule we treat SUNAT itself as the source
of truth on existence; we only enforce length + digit-only format.

Name search: SUNAT supports name (razón social) search via the same JSP
with `accion=consPorRazonSocial`, but the form requires a CAPTCHA token
generated by the parent page. Without solving the CAPTCHA we cannot
return real results, so `search_by_name` raises
`AdapterNotImplementedError`. Use direct RUC lookup.
"""
from __future__ import annotations

import html
import re
from datetime import date, datetime
from typing import Any

import httpx

from packages.adapters._base.adapter import CountryAdapter
from packages.adapters._base.errors import (
    AdapterNotImplementedError,
    BlockedByRegistryError,
    InvalidIdentifierError,
)
from packages.adapters._base.http import build_http_client, get_with_retry
from packages.shared.models import (
    AdapterHealth,
    AdapterStatus,
    CompanyDetails,
    CompanyMatch,
    FilingType,
    FinancialFiling,
    IdentifierType,
    RegistryIdentifier,
)

_DIGITS_RE = re.compile(r"\D+")
_RUC_RE = re.compile(r"^\d{11}$")
_TAG_RE = re.compile(r"<[^>]+>")
_WS_RE = re.compile(r"\s+")


def _normalize_ruc(value: str) -> str:
    """Strip "PE"/whitespace/punctuation, validate length + digit-only.

    Raises `InvalidIdentifierError` on bad input. See module docstring for
    why we do not enforce a Mod-11 checksum here.
    """
    raw = (value or "").strip().upper()
    if raw.startswith("PE"):
        raw = raw[2:]
    cleaned = _DIGITS_RE.sub("", raw)
    if not _RUC_RE.match(cleaned):
        raise InvalidIdentifierError(
            f"Peruvian RUC must be 11 digits: {value!r}"
        )
    return cleaned


def _strip_html(body: str) -> str:
    no_tags = _TAG_RE.sub(" ", body)
    decoded = html.unescape(no_tags)
    return _WS_RE.sub(" ", decoded).strip()


class PEAdapter(CountryAdapter):
    country_code = "PE"
    country_name = "Peru"
    identifier_types = [IdentifierType.VAT, IdentifierType.COMPANY_NUMBER]
    primary_identifier = IdentifierType.VAT
    requires_api_key = False
    api_key_env = None
    rate_limit_per_minute = 30

    SUNAT_BASE = "https://e-consultaruc.sunat.gob.pe"
    SUNAT_PATH = "/cl-ti-itmrconsruc/jcrS00Alias"
    SMV_FILINGS_URL = "https://www.smv.gob.pe/Frm_InformacionFinanciera.aspx"

    # Cementos Pacasmayo — used as a stable canary for SUNAT health probes.
    _HEALTH_RUC = "20419387658"

    async def health_check(self) -> AdapterHealth:
        try:
            async with self._sunat_client() as client:
                resp = await get_with_retry(
                    client,
                    self.SUNAT_PATH,
                    params=self._sunat_params(self._HEALTH_RUC),
                )
        except Exception as exc:
            return AdapterHealth(
                country_code=self.country_code,
                name=self.country_name,
                status=AdapterStatus.ERROR,
                capabilities={"search": False, "lookup": False, "financials": False},
                notes=str(exc)[:200],
            )
        body = resp.text or ""
        if _is_captcha_response(body):
            return AdapterHealth(
                country_code=self.country_code,
                name=self.country_name,
                status=AdapterStatus.BLOCKED,
                capabilities={"search": False, "lookup": False, "financials": True},
                rate_limit_per_minute=self.rate_limit_per_minute,
                notes=(
                    "SUNAT JSP requires CAPTCHA token; direct HTTP lookup "
                    "blocked. SMV filings URL still available for listed entities."
                ),
            )
        if resp.status_code >= 500:
            return AdapterHealth(
                country_code=self.country_code,
                name=self.country_name,
                status=AdapterStatus.ERROR,
                capabilities={"search": False, "lookup": False, "financials": False},
                notes=f"SUNAT returned HTTP {resp.status_code}",
            )
        return AdapterHealth(
            country_code=self.country_code,
            name=self.country_name,
            status=AdapterStatus.OK,
            capabilities={"search": False, "lookup": True, "financials": True},
            rate_limit_per_minute=self.rate_limit_per_minute,
            notes=(
                "Name search unavailable (SUNAT name lookup requires CAPTCHA). "
                "Financials limited to SMV-supervised entities (URL only)."
            ),
        )

    async def search_by_name(self, name: str, limit: int = 10) -> list[CompanyMatch]:
        raise AdapterNotImplementedError(
            "SUNAT name search (consPorRazonSocial) requires a CAPTCHA token "
            "generated by the parent page; without solving it we cannot return "
            "real data. Use direct RUC lookup."
        )

    async def lookup_by_identifier(
        self, id_type: IdentifierType, value: str
    ) -> CompanyDetails | None:
        if id_type not in (IdentifierType.VAT, IdentifierType.COMPANY_NUMBER):
            raise InvalidIdentifierError(
                f"PE only supports VAT/COMPANY_NUMBER (RUC), got {id_type}"
            )
        ruc = _normalize_ruc(value)

        try:
            async with self._sunat_client() as client:
                resp = await get_with_retry(
                    client,
                    self.SUNAT_PATH,
                    params=self._sunat_params(ruc),
                )
        except httpx.HTTPError as exc:
            raise BlockedByRegistryError(
                f"SUNAT transport error for RUC {ruc}: {exc}"
            ) from exc

        if resp.status_code == 404:
            return None
        if resp.status_code >= 500:
            raise BlockedByRegistryError(
                f"SUNAT returned HTTP {resp.status_code} for RUC {ruc}"
            )

        body = resp.text or ""
        if _is_captcha_response(body):
            raise BlockedByRegistryError(
                "SUNAT JSP requires CAPTCHA token; direct HTTP lookup blocked. "
                "A browser/captcha-solving pipeline is required."
            )

        parsed = _parse_sunat_response(body)
        if parsed is None:
            return None

        identifiers = [
            RegistryIdentifier(type=IdentifierType.VAT, value=ruc, label="RUC"),
            RegistryIdentifier(
                type=IdentifierType.COMPANY_NUMBER, value=ruc, label="RUC"
            ),
        ]

        return CompanyDetails(
            id=ruc,
            name=parsed.get("name") or ruc,
            country="PE",
            legal_form=parsed.get("contributor_type"),
            status=parsed.get("status"),
            registered_address=parsed.get("address"),
            nace_codes=parsed.get("activity_codes", []),
            identifiers=identifiers,
            raw={
                "ruc": ruc,
                "contributor_type": parsed.get("contributor_type"),
                "status": parsed.get("status"),
                "condition": parsed.get("condition"),
                "address": parsed.get("address"),
                "activity": parsed.get("activity"),
                "source": "sunat.e-consultaruc",
            },
            source_url=(
                f"{self.SUNAT_BASE}{self.SUNAT_PATH}"
                f"?accion=consPorRuc&nroRuc={ruc}"
            ),
        )

    async def fetch_financials(
        self, company_id: str, years: int = 5
    ) -> list[FinancialFiling]:
        ruc = _normalize_ruc(company_id)
        # SMV only supervises listed/regulated entities. We cannot tell from
        # outside whether a given RUC is listed without making a request; the
        # discovery URL loads an empty result page for non-listed firms. Per
        # the no-mock-data rule, surface the SMV discovery URL only if the
        # page reports at least one filed report. The cheap and safe option
        # is to probe once and let the response tell us.
        discovery_url = f"{self.SMV_FILINGS_URL}?data={ruc}"
        try:
            async with build_http_client(timeout=20.0) as client:
                resp = await get_with_retry(client, discovery_url)
        except httpx.HTTPError:
            return []

        if resp.status_code >= 500 or resp.status_code == 404:
            return []
        body = resp.text or ""
        if not _smv_has_filings(body):
            return []

        current_year = datetime.utcnow().year
        filings: list[FinancialFiling] = []
        for offset in range(years):
            yr = current_year - 1 - offset
            filings.append(
                FinancialFiling(
                    company_id=ruc,
                    year=yr,
                    type=FilingType.ANNUAL_REPORT,
                    period_end=date(yr, 12, 31),
                    currency="PEN",
                    structured_data=None,
                    document_url=discovery_url,
                    document_format="html",
                    source_url=discovery_url,
                )
            )
        return filings

    def _sunat_client(self) -> httpx.AsyncClient:
        return build_http_client(
            base_url=self.SUNAT_BASE,
            headers={
                "Accept": "text/html,application/xhtml+xml",
                "Accept-Language": "es-PE,es;q=0.9,en;q=0.7",
            },
            timeout=25.0,
        )

    @staticmethod
    def _sunat_params(ruc: str) -> dict[str, str]:
        return {"accion": "consPorRuc", "nroRuc": ruc}


def _is_captcha_response(body: str) -> bool:
    lowered = body.lower()
    return (
        "captcha" in lowered
        or "código de captcha" in lowered
        or "codigo de captcha" in lowered
        or "txtcodigo" in lowered
        and "consporruc" not in lowered
    )


def _smv_has_filings(body: str) -> bool:
    """Heuristic: SMV's "no data" page renders a Spanish empty-result notice.

    We treat the presence of an annual-report label ("Información Financiera
    Anual" / "Memoria Anual") as evidence the RUC is supervised.
    """
    text = _strip_html(body).lower()
    return any(
        token in text
        for token in (
            "información financiera anual",
            "informacion financiera anual",
            "memoria anual",
            "estados financieros auditados",
        )
    )


def _parse_sunat_response(body: str) -> dict[str, Any] | None:
    """Best-effort scrape of the SUNAT consPorRuc result.

    The result page is a small two-column table with Spanish labels. Layout
    has changed multiple times since the 2010s, so we match against label
    text and capture the following value run. Never fabricate values: if
    the name label isn't present, return None and let the caller treat the
    RUC as not-found.
    """
    if not body or "<" not in body:
        return None

    text = _strip_html(body)
    if not text:
        return None

    # SUNAT's "RUC no existe" page is short and lacks the Nombre/Razón label.
    lowered = text.lower()
    if "no existe" in lowered and "razón social" not in lowered and "razon social" not in lowered:
        return None

    name = _extract_label(
        text,
        labels=(
            "Número de RUC:",
            "Numero de RUC:",
        ),
        # Inside SUNAT pages the RUC line reads "RUC: 20100068133 - CREDICORP CAPITAL S.A."
        post_strip="- ",
    )
    if name and " - " in name:
        name = name.split(" - ", 1)[1].strip()

    if not name:
        name = _extract_label(
            text,
            labels=(
                "Razón Social:",
                "Razon Social:",
                "Nombre o Razón Social:",
                "Nombre Comercial:",
            ),
        )

    if not name:
        return None

    contributor_type = _extract_label(
        text,
        labels=("Tipo Contribuyente:", "Tipo de Contribuyente:"),
    )
    status = _extract_label(text, labels=("Estado del Contribuyente:", "Estado:"))
    condition = _extract_label(
        text, labels=("Condición del Contribuyente:", "Condición:", "Condicion:")
    )
    address = _extract_label(
        text,
        labels=("Domicilio Fiscal:", "Dirección:", "Direccion:"),
    )
    activity = _extract_label(
        text,
        labels=(
            "Actividad(es) Económica(s):",
            "Actividades Económicas:",
            "Actividad Económica Principal:",
        ),
    )

    activity_codes: list[str] = []
    if activity:
        for m in re.finditer(r"(?<!\d)(\d{4,6})(?!\d)", activity):
            activity_codes.append(m.group(1))

    return {
        "name": name,
        "contributor_type": contributor_type,
        "status": status,
        "condition": condition,
        "address": address,
        "activity": activity,
        "activity_codes": activity_codes,
    }


def _extract_label(
    text: str, *, labels: tuple[str, ...], post_strip: str = " :-\t"
) -> str | None:
    """Find first label; return the value run until the next label or 200 chars.

    The SUNAT page labels are always followed by the value on the same row;
    after HTML stripping they appear as `"<Label>: <value>   <Label2>: ..."`.
    """
    boundary = re.compile(
        r"\s{2,}|(?="
        r"Tipo Contribuyente:|Tipo de Contribuyente:|"
        r"Nombre Comercial:|Fecha de Inscripción:|Fecha de Inicio de Actividades:|"
        r"Estado del Contribuyente:|Estado:|"
        r"Condición del Contribuyente:|Condici[oó]n:|"
        r"Domicilio Fiscal:|Direcci[oó]n:|"
        r"Actividad\(es\) Econ[oó]mica\(s\):|Actividades Econ[oó]micas:|"
        r"Actividad Econ[oó]mica Principal:|"
        r"Sistema Emisi[oó]n de Comprobante:|N[uú]mero de RUC:|Raz[oó]n Social:"
        r")"
    )
    for label in labels:
        idx = text.lower().find(label.lower())
        if idx < 0:
            continue
        rest = text[idx + len(label) :].lstrip(post_strip)
        if not rest:
            continue
        parts = boundary.split(rest, maxsplit=1)
        candidate = (parts[0] if parts else rest).strip(" :,-\t")
        if candidate:
            return candidate[:300]
    return None
