export const FLAGS: Record<string, string> = {
  GB: "🇬🇧", UK: "🇬🇧", US: "🇺🇸", FR: "🇫🇷", DE: "🇩🇪", PL: "🇵🇱",
  NL: "🇳🇱", IT: "🇮🇹", ES: "🇪🇸", BE: "🇧🇪", SE: "🇸🇪", NO: "🇳🇴",
  DK: "🇩🇰", FI: "🇫🇮", IE: "🇮🇪", AT: "🇦🇹", CZ: "🇨🇿", SK: "🇸🇰",
  HU: "🇭🇺", RO: "🇷🇴", BG: "🇧🇬", HR: "🇭🇷", SI: "🇸🇮", LT: "🇱🇹",
  LV: "🇱🇻", EE: "🇪🇪", PT: "🇵🇹", LU: "🇱🇺", MT: "🇲🇹", CY: "🇨🇾",
  GR: "🇬🇷", TR: "🇹🇷",
};

export const IDENTIFIER_LABELS: Record<string, { primary: string; placeholder: string }> = {
  GB: { primary: "Company Number", placeholder: "e.g. 00102498" },
  UK: { primary: "Company Number", placeholder: "e.g. 00102498" },
  US: { primary: "CIK", placeholder: "e.g. 0000320193" },
  FR: { primary: "SIREN", placeholder: "e.g. 542051180" },
  DE: { primary: "HRB", placeholder: "e.g. HRB 42243" },
  PL: { primary: "KRS", placeholder: "e.g. 0000028860" },
  NL: { primary: "KvK", placeholder: "e.g. 17014545" },
  IT: { primary: "VAT", placeholder: "e.g. IT00484960588" },
  ES: { primary: "CIF", placeholder: "e.g. A15022510" },
  SE: { primary: "Org.nr", placeholder: "e.g. 556012-5790" },
  NO: { primary: "Org.nr", placeholder: "e.g. 923609016" },
  DK: { primary: "CVR", placeholder: "e.g. 24256790" },
  FI: { primary: "Y-tunnus", placeholder: "e.g. 0112038-9" },
  IE: { primary: "Company Number", placeholder: "e.g. 12345" },
  AT: { primary: "FN", placeholder: "" },
  CZ: { primary: "IČO", placeholder: "e.g. 27082440" },
  SK: { primary: "IČO", placeholder: "" },
  HU: { primary: "Cégjegyzékszám", placeholder: "" },
  RO: { primary: "CUI", placeholder: "" },
  BG: { primary: "EIK", placeholder: "" },
  HR: { primary: "OIB", placeholder: "" },
  SI: { primary: "Matična št.", placeholder: "" },
  LT: { primary: "Įmonės kodas", placeholder: "" },
  LV: { primary: "Reģ. Nr.", placeholder: "" },
  EE: { primary: "Registrikood", placeholder: "" },
  PT: { primary: "NIPC", placeholder: "" },
  LU: { primary: "RCSL", placeholder: "" },
  MT: { primary: "MBR No.", placeholder: "" },
  CY: { primary: "Reg. No.", placeholder: "" },
  GR: { primary: "GEMI", placeholder: "" },
  TR: { primary: "VKN", placeholder: "e.g. 8350023902" },
};
